/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MyApp;

import MyLibs.User;
import java.util.ArrayList;
import javax.swing.JLabel;

/**
 *
 * @author killa
 */
public class AppForm extends javax.swing.JFrame {
    private ArrayList<Object[]> userInfoList;
    
    private static User user;
    
    /**
     * Creates new form AppForm
     */
    public AppForm() {
        // create user info list
        userInfoList = new ArrayList<>();
        userInfoList.add(new Object[] {"Dannie421", "cheezits", 0});
        userInfoList.add(new Object[] {"Yvonne24", "appalachia", 0});
        userInfoList.add(new Object[] {"Tim", "codex834", 1});
        
        // initialize frame properties
        initComponents();
        
        this.add(new LoginPage(getContentPane()));
        
        // center window
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginErrorMessageLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Asset Acquisition & Monitoring System");
        setBackground(new java.awt.Color(55, 61, 71));
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/assets/icon-2.png")).getImage()
        );
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);

        loginErrorMessageLabel.setBackground(new java.awt.Color(0, 0, 0));
        loginErrorMessageLabel.setFont(new java.awt.Font("Georgia", 1, 15)); // NOI18N
        loginErrorMessageLabel.setForeground(new java.awt.Color(78, 87, 101));
        loginErrorMessageLabel.setText("Incorrect Log-in details");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(193, 193, 193)
                .addComponent(loginErrorMessageLabel)
                .addContainerGap(193, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(397, Short.MAX_VALUE)
                .addComponent(loginErrorMessageLabel)
                .addGap(102, 102, 102))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppForm().setVisible(true);
            }
        });
    }

    public void useJPanel(javax.swing.JPanel panel) {
         javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );   
        
        pack();
        
        setLocationRelativeTo(null);
    }
    
    public ArrayList<Object[]> getUserInfoList() {
        return userInfoList;
    }

    public JLabel getLoginErrorMessageLabel() {
        return loginErrorMessageLabel;
    }

    public static User getUser() {
        return user;
    }

    public static void setUser(User user) {
        AppForm.user = user;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel loginErrorMessageLabel;
    // End of variables declaration//GEN-END:variables
}
